### ISSUE TITLE
Uncaught TypeError: Argument 1 throws an exception during search indexing

### ISSUE THREAD

**Issue by shaneonabike** [agileware/content-views-civicrm-data-processor#10] opened 2020-08-20 02:06 UTC
Overview
----------------------------------------
We are using ElasticSearch (ElasticPress) to index our site. I know that in the latest CiviCRM it creates a page (ID: 5) which should not be deleted. For some weird reason this page (I believe) is causing exceptions although I could be wrong. If there is a way that I can output a bigger stacktrace let me know and I'll provide that. I honestly can't determine where this is originating from which is frustrating.

Regardless, each time that I index it hangs because an exception is thrown during the index process. I can confirm now that disabling the plugin results in no more errors. As a side note, I don't have _any_ views setup.

Reproduction steps
----------------------------------------
1. Install ElasticPress
1. Connect to your ElasticSearch
1. Index the website and receive an error

`Uncaught TypeError: Argument 1 passed to civicrm_api3() must be of the type string, null given, called in /var/www/example.org/wp-content/plugins/content-views-civicrm-data-processor/includes/class-cvc-api.php on line 27 and defined in /var/www/example.org/wp-content/plugins/civicrm/civicrm/api/api.php:129
Stack trace:

#0 /var/www/example.org/wp-content/plugins/content-views-civicrm-data-processor/includes/class-cvc-api.php(27): civicrm_api3(NULL, 'getfields', Array)

#1 /var/www/example.org/wp-content/plugins/content-views-civicrm-data-processor/includes/class-cvc-api.php(49): Content_Views_CiviCRM_Api->call(NULL, 'getfields', Array)

#2 /var/www/example.org/wp-content/plugins/content-views-civicrm-data-processor/includes/class-cvc-display.php(256): Content_Views_CiviCRM_Api->call_values(NULL, 'getfields', Array)

#3 /var/www/example.org/wp-content/plugins/content-views-civicrm-data-processor/includes/class-cvc-display.php(180): Content_Views_CiviCRM_Display->get_fields in /var/www/example.org/wp-content/plugins/civicrm/civicrm/api/api.php on line 129`

Current behaviour
----------------------------------------

Expected behaviour
----------------------------------------
I was expecting that if bad values are sent to CiviCRM it could just gracefully fail instead of throwing an exception.

Environment information
----------------------------------------

* __Browser:__ _Firefox 59.0.1/Chrome 78.0.3904/Safari 13_
* __CiviCRM:__ Latest
* __PHP:__ 7.2
* __CMS:__ Wordpress
* __Web Server:__ Nginx Latest

**Comment by agileware-justin** [comment] 2020-08-20 03:58
@shaneonabike how do you feel about providing us with access to a development environment with this set up, so we can see what's going on?

**Comment by shaneonabike** [comment] 2020-08-21 18:30
It would take a bit of time for me to get approval for you to have access so I think I would to say presently I cannot. But I would be happy to provide additional debugging if you want me to troubleshoot. I have disable the module at present to prevent the errors.

I think it should be easy to find the calls being made that aren't being caught and maybe upgrade them also to v4 since I thought that the old api is becoming deprecated non?

**Comment by agileware-justin** [comment] 2020-08-21 21:42
@shaneonabike here are some suggestions to help us find out what is going on here:

1. Provide a screenshot of the Content Views configuration and related CiviCRM custom fields (if used)
2. Provide access to a development environment, where the problem is reproducible - this does not need to be a copy of your production environment. Can CiviCRM with sample data, WordPress with example pages and Elastic Search integrated

We use this plugin in production, on multiple websites so am confident that it does work. Being able to debug your specific issue, needs more information than what has been provided thus far.

If you (or your customer) wants to contract our support services to solve this issue then contact me at sales@agileware.com.au and I can provide a quote.

I'll leave this issue open for now and if no further information is provided by you, will mark this as closed.

Best wishes from Australia!

**Comment by shaneonabike** [comment] 2020-08-22 01:45
Actually there isn't any view ;) There are custom fields in CiviCRM that I can definitely show you. I think the point of my post is that this really should never reached if I'm not really using it right?

Thanks for the offer for support, but I'm actually the CiviCRM / Wordpress developer and I _think_ my original attempt was to help you folks figure out a fairly serious bug. When you indicated that this  is installed on several sites does they include ElasticSearch? If not you could easily reproduce this by setting that up I believe. I'll try and track down the issue when I get a chance with some properly inline debugging in your code.

**Comment by agileware-justin** [comment] 2020-08-22 02:19
Righto, I'll close this issue and if you ever track down what's going on, feel free to open a new one and reference this one too. Have a good one!

**Closed as completed by agileware-justin** 2020-08-22 02:19 UTC
Labels: question
